version: 6.0.{build}
branches:
  only:
  - master
  - development
skip_tags: true
skip_branch_with_pr: true
max_jobs: 1
image: Visual Studio 2022
configuration: Release
environment:
  NUGET_API_KEY:
    secure: q3PXM+sPsIafsbjXN/Mfid0mgsHq+hCC+yo4pZ4hTbPYeey1UspQCrTHba62wtKM
build: off
build_script:
- ps: >-
    $packVersion = $env:APPVEYOR_BUILD_VERSION

    if ($env:APPVEYOR_REPO_BRANCH -ieq "development") {
        $packVersion += "-beta"
    }

    dotnet pack -c "Release" -p:Version=$packVersion

    if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) {
      dotnet nuget push ".\PetaPoco\bin\Release\*.nupkg" -k "$($env:NUGET_API_KEY)" -s "https://www.nuget.org/api/v2/package"
    }
test: off
